require('./wi-icons');
module.exports = {
  editable: require('./editable'),
  sideBar : require('./side-bar/index'),
  lineStyle: require('./line-style/index'),
  sortable: require('./wi-sortable/index'),
  wiBaseTreeview : require('./wi-base-treeview/wi-base-treeview'),
  wiLogin: require('./wi-login/wi-login'),
  wiToken: require('./wi-token/index'),
  wiSession: require('./wi-session'),
  katexView: require('./katex-view'),
  wiTableView: require('./wi-table-view'),
  wiTreeView: require('./wi-tree-view'),
  wiDroppable: require('./wi-droppable'),
  wiDialog: require('./wi-dialog'),
  wiApi: require('./wi-api'),
  wiLoading: require('./wi-loading'),
  wiDropdownList: require('./wi-dropdown-list'),
  wiAutocomplete: require('./wi-autocomplete'),
  wiDiscriminator: require('./wi-discriminator'),
  wiMapLoading: require('./wi-map-loading'),
  wiPrintLoading: require('./wi-print-loading'),
  wiTreeViewVirtual: require('./wi-tree-view-virtual'),
  wiNeuralNetwork: require('./wi-neural-network'),
  wiPrintTable: require('./wi-printable'),
  imgPreview: require('./img-preview'),
  wiTableResizeable: require('./wi-table-resizeable'),
  wiFrequency: require('./wi-frequency'),
  wiSlideshow: require('./wi-slideshow'),
  wiLabeledInput: require('./wi-labeled-input'),
  chartWidget: require('./chart-widget'),
  managerDashboard: require('./manager-dashboard'),
  wiImportCsvFile: require('./wi-import-csv-file/wi-import-csv-file'),
  virtualUl: require('./virtual-ul'),
  treeExplorer: require('./tree-explorer'),
  wiDeviceRequirement: require('./wi-device-requirement')
}
